---
- name: Install php-fpm and deps 
  yum: name={{ item }} state=latest enablerepo=remi,remi-php55
  with_items:    
    - php-fpm
    - php-common
    - php-devel
    - php-cli
    - php-pdo
    - php-gd
    - php-xml
    - php-mbstring
    - php-mcrypt

- name: Copy www.conf file
  template: src=www.conf dest=/etc/php-fpm.d/www.conf

- name: Add php-fpm to chkconfig
  command: chkconfig --add php-fpm

- name: Auto start php-fpm
  command: chkconfig --levels 235 php-fpm on
  notify: restart php-fpm